# Usa la imagen base oficial de pgAdmin4
FROM dpage/pgadmin4

# Define variables de entorno para la configuración predeterminada de pgAdmin4
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=admin

# Exponer el puerto 80 para pgAdmin4
EXPOSE 80
