# Usa la imagen base oficial de PostgreSQL
FROM postgres

# Variables de entorno para la configuración de PostgreSQL
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin
ENV POSTGRES_DB=admindb

# Exponer el puerto 5432 para PostgreSQL
EXPOSE 5432
